/* Generated by npm run web:build. Do not edit manually. */
const CACHE_PREFIX = "pokeidle";
const SHELL_CACHE_NAME = "pokeidle-shell-v0.1.56";
const RUNTIME_CACHE_NAME = "pokeidle-runtime-v0.1.56";
const SHELL_URLS = [
  "./",
  "./assets/icons/pokeball-dock.png",
  "./core/runtime-binding-resolver.js",
  "./core/runtime-bootstrap-system.js",
  "./core/runtime-composition-root.js",
  "./core/runtime-loop-kernel.js",
  "./core/runtime-orchestrator.js",
  "./domain/combat/balance-rules.js",
  "./domain/encounter/shiny-rules.js",
  "./domain/progression/reward-rules.js",
  "./domain/routes/route-timer-rules.js",
  "./game-design-config.js",
  "./game-runtime.js",
  "./game.js",
  "./index.html",
  "./infra/storage/browser-save-storage.js",
  "./infra/storage/desktop-bridge-save-storage.js",
  "./infra/storage/indexeddb-save-storage.js",
  "./lib/audio-manager.js",
  "./lib/ball-capture-menu-config.js",
  "./lib/browser-save-utils.js",
  "./lib/combat-balance-config.js",
  "./lib/combat-passives.js",
  "./lib/combat-vfx-config.js",
  "./lib/compact-save-codec.js",
  "./lib/dev-layout-controls.js",
  "./lib/environment-runtime.js",
  "./lib/game-design-config-runtime.js",
  "./lib/game-math-runtime.js",
  "./lib/game-runtime-state.js",
  "./lib/game-world-config.js",
  "./lib/gameplay-ui-config.js",
  "./lib/github-update-checker.js",
  "./lib/maintenance-bootstrap.js",
  "./lib/number-utils.js",
  "./lib/pokedex-display-config.js",
  "./lib/pokemon-core-utils.js",
  "./lib/render-quality-utils.js",
  "./lib/route-navigation-runtime.js",
  "./lib/runtime-config-loaders.js",
  "./lib/runtime-data.js",
  "./lib/runtime-platform-utils.js",
  "./lib/runtime-stage-layout.js",
  "./lib/runtime-version-config.js",
  "./lib/save-consistency.js",
  "./lib/save-runtime-config.js",
  "./lib/save-transfer-utils.js",
  "./lib/shop-config-factory.js",
  "./lib/shop-config-runtime.js",
  "./lib/stats-config.js",
  "./lib/talents.js",
  "./lib/text-normalization.js",
  "./lib/type-combat-data.js",
  "./lib/ui-animation-runtime.js",
  "./lib/ui-text-normalization-runtime.js",
  "./lib/ui-tween-config.js",
  "./lib/wallet-ui-runtime.js",
  "./lib/zone-dialogue-runtime.js",
  "./lib/zone-graph-runtime.js",
  "./styles.css",
  "./systems/combat/battle-lifecycle-system.js",
  "./systems/combat/pokemon-battle-manager.js",
  "./systems/encounter/route-encounter-combat-system.js",
  "./systems/notifications/runtime-notification-system.js",
  "./systems/progression/reward-progression-system.js",
  "./systems/save/runtime-save-system.js",
  "./systems/ui/map-navigation-ui.js",
  "./systems/ui/route-navigation-ui.js",
  "./systems/ui/runtime-hud-system.js",
  "./systems/ui/runtime-input-system.js",
  "./systems/ui/runtime-render-system.js",
  "./systems/ui/runtime-ui-dom-factory.js",
  "./systems/ui/runtime-ui-interaction-system.js",
  "./systems/ui/zone-dialogue-ui.js",
  "./vendor/howler.js",
  "./vendor/omggif.js",
  "./vendor/pako.min.js",
  "./vendor/papaparse.js",
  "./vendor/tween.js",
  "./vendor/upng.js",
  "./vendor/zod.js",
  "./version.js"
];
const SAME_ORIGIN_STATIC_DESTINATIONS = new Set(["script", "style", "image", "font", "audio", "video", "manifest", "worker"]);

function isBypassedRequest(requestUrl, request) {
  if (!request || request.method !== "GET") {
    return true;
  }
  if (requestUrl.origin !== self.location.origin) {
    return true;
  }
  if (String(request.cache || "").toLowerCase() === "no-store") {
    return true;
  }
  return requestUrl.pathname.endsWith("/maintenance-config.js");
}

function isNavigationRequest(request) {
  return request.mode === "navigate";
}

function isSameOriginStaticRequest(requestUrl, request) {
  if (requestUrl.origin !== self.location.origin) {
    return false;
  }
  if (isNavigationRequest(request)) {
    return false;
  }
  if (SAME_ORIGIN_STATIC_DESTINATIONS.has(String(request.destination || "").toLowerCase())) {
    return true;
  }
  const extension = requestUrl.pathname.split(".").pop()?.toLowerCase() || "";
  return ["js", "mjs", "css", "json", "csv", "png", "jpg", "jpeg", "gif", "svg", "ico", "webp", "wav", "mp3", "ogg"].includes(extension);
}

async function purgeLegacyCaches() {
  const cacheNames = await caches.keys();
  await Promise.all(
    cacheNames
      .filter((cacheName) => cacheName.startsWith(CACHE_PREFIX) && cacheName !== SHELL_CACHE_NAME && cacheName !== RUNTIME_CACHE_NAME)
      .map((cacheName) => caches.delete(cacheName)),
  );
}

self.addEventListener("install", (event) => {
  event.waitUntil((async () => {
    const shellCache = await caches.open(SHELL_CACHE_NAME);
    await shellCache.addAll(SHELL_URLS);
    await self.skipWaiting();
  })());
});

self.addEventListener("activate", (event) => {
  event.waitUntil((async () => {
    await purgeLegacyCaches();
    await self.clients.claim();
  })());
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  const requestUrl = new URL(request.url);
  if (isBypassedRequest(requestUrl, request)) {
    return;
  }

  if (isNavigationRequest(request)) {
    event.respondWith((async () => {
      const shellCache = await caches.open(SHELL_CACHE_NAME);
      try {
        const networkResponse = await fetch(request);
        if (networkResponse && networkResponse.ok) {
          await shellCache.put(request, networkResponse.clone());
        }
        return networkResponse;
      } catch {
        const cachedResponse = await shellCache.match(request);
        if (cachedResponse) {
          return cachedResponse;
        }
        const cachedIndex = await shellCache.match("./index.html");
        if (cachedIndex) {
          return cachedIndex;
        }
        throw new Error("Offline shell unavailable.");
      }
    })());
    return;
  }

  if (!isSameOriginStaticRequest(requestUrl, request)) {
    return;
  }

  event.respondWith((async () => {
    const runtimeCache = await caches.open(RUNTIME_CACHE_NAME);
    const cachedResponse = await runtimeCache.match(request);
    if (cachedResponse) {
      return cachedResponse;
    }
    const networkResponse = await fetch(request);
    if (networkResponse && networkResponse.ok) {
      await runtimeCache.put(request, networkResponse.clone());
    }
    return networkResponse;
  })());
});
